### ISSUE TITLE
The file refresh strategy could be improved to download content only when it's newer.

### ISSUE THREAD

**Issue by eapl-gemugami** [sorenpeter/timeline#10]
I discovered that the current refresh strategy does not consider the HTTP headers `If-Modified-Since` in the request and `Last-Modified` in the response. Instead, it always downloads all the content, even if there have been no changes since the last refresh.

I am creating this issue to notify that I intend to work on this improvement.

**Comment by sorenpeter** [comment]
Yeah, great idea. I have no idea how to make this:)
