### ISSUE TITLE
Hashtags are ignoring special characters like accents

### ISSUE THREAD

**Issue by eapl-gemugami** [sorenpeter/timeline#12]
In a twt, hashtags don't take into consideration common characters like accented vowels in Spanish
![image](https://github.com/user-attachments/assets/a6f20f6f-1c52-4368-9a49-1f5ed52f6b3e)
for example `queMoci` should be `queMoción` and `rantDelD` should be `rantDelDía`

It affects the `tag_cloud` as well
![image](https://github.com/user-attachments/assets/ede7ed70-71c4-4d37-a32e-2566e6dee112)

I found that the regex here:
[libs/twtxt.php - getTagsFromTwt](https://github.com/sorenpeter/timeline/blob/main/libs/twtxt.php#L127)

```php
$pattern = '/(?<=\B)#(\w+)/';
```

...is pretty limited as it only allows characters a-z, A-Z, 0-9, including _ (underscore).

Looking for options, I found the following SO question: [_Actual_ Twitter format for hashtags? ...](https://stackoverflow.com/questions/8451846/actual-twitter-format-for-hashtags-not-your-regex-not-his-code-the-actual)

It's outdated although it took me to the following expression
`\B(?:#|＃)((?![\p{N}_]+(?:$|\b|\s))(?:[\p{L}\p{M}\p{N}_]{1,60}))`
which seems to work in https://regex101.com, although more tests would be required (at least for Spanish).

**Comment by eapl-gemugami** [comment]
Trying with the following: `$pattern = '/(?<=\B)#([\p{L}\p{N}_]+)/u';`

It's looking good: [#queMoción](http://localhost:8000/://localhost:8000/profile&search=queMoci%C3%B3n) [#rantDelDía](http://localhost:8000/://localhost:8000/profile&search=rantDelD%C3%ADa)

It also has to be replaced in `twtxt.php` inside the function `replaceTagsFromTwt()`

**Comment by sorenpeter** [comment]
Hi, It should be fixed now in main. And thanks for noticing:)

**Comment by eapl-gemugami** [comment]
He, I tried to push it but was late yesterday, thanks for fixing it :)

**Comment by eapl-gemugami** [comment]
Currently I'm using my pod (.mx) as a sandbox for development, although I should update it soon, thanks!
