### ISSUE TITLE
In 'following' what does Time ago mean?

### ISSUE THREAD

**Issue by eapl-gemugami** [sorenpeter/timeline#14]
I find that each follower has a **Time ago** column
![image](https://github.com/user-attachments/assets/7716f926-d6a3-4125-b43f-537719f4aac8)

What does that mean? When was the last twt found for each URL?

I think it's a good opportunity to also check for down URLs.

**Comment by eapl-gemugami** [comment]
I see you've closed it, as the question is answered, although we still have the Warning when trying to read a faulty file.
Should we open another for that Warning then?

**Comment by sorenpeter** [comment]
Yes good idea
