### ISSUE TITLE
Html Code Element breaking layout

### ISSUE THREAD

**Issue by aelaraji** [sorenpeter/timeline#22]
The HTML `<code>` Element tend to break the page's layout, overflowing out of parent elements instead of having a slider. 

see twtxt conversation `(#kf6wlbq)` for example.

**Comment by sorenpeter** [comment]
Yeah it have also be buggin me. shoud be fixed now in: https://github.com/sorenpeter/timeline/commit/1adfa39cfd0222187b5460ae9a15599a39ea15ab
