### ISSUE TITLE
commented line maybe causing issue after a refresh

### ISSUE THREAD

**Issue by aelaraji** [sorenpeter/timeline#23]
Is [this line](https://github.com/sorenpeter/timeline/blame/97a97122bb3ed8ea760342be8cc3760ab5c35449/views/refresh.php#L10) commented on purpose? 
It may be causing timeline to complain about not having a buffer for [ob_end_flush()](https://github.com/sorenpeter/timeline/blame/97a97122bb3ed8ea760342be8cc3760ab5c35449/views/refresh.php#L14) on the same file, to delete or flush.

un-commentating it stopped the Notice from popping up on my instance, but I'm not sure if that could have other side-effects.

![2024-12-12_18-35-38_955x229](https://github.com/user-attachments/assets/25d69217-4d9a-4dae-a977-ef4b838eff19)

**Comment by eapl-gemugami** [comment]
I'm seeing the same behaviour in the sandbox instance:
https://twtxt-sandbox.eapl.me/timeline/

![Capture d’écran du 2024-12-12 16-56-58](https://github.com/user-attachments/assets/7a0edbf4-1455-4365-86c7-0f425f3d4cde)

I'll take a look into it

**Comment by sorenpeter** [comment]
Can it be a problem on your servers? I don't see it anymore, but I remeber having it when I made the refresh page.
