### ISSUE TITLE
Warnings on the /webmention endpoint

### ISSUE THREAD

**Issue by aelaraji** [sorenpeter/timeline#28]
These are caused by the $config variable not being defined in the webmentions_endpoint.php file. 

    - Warning: Undefined variable $config in /usr/share/nginx/html/main/timeline/views/webmention_endpoint.php on line 8
    - Warning: Trying to access array offset on null in /usr/share/nginx/html/main/timeline/views/webmention_endpoint.php on line 8

they could be fixed either by adding in `$config = parse_ini_file('private/config.ini');` or `require_once("partials/base.php");` before declaring `$logfile`.

This one is caused by the `Please send a propper webmention to this endpoint` message being sent by the `print();` before the `header();` could send it's `400 Bad Request`, as a result the client gets a `Status 200` instead and Timeline complains with the following Warning:

    - Warning: Cannot modify header information - headers already sent by (output started at /usr/share/nginx/html/main/timeline/views/webmention_endpoint.php:8) in /usr/share/nginx/html/main/timeline/views/webmention_endpoint.php on line 13

**Comment by eapl-gemugami** [comment]
I think we could close this one @aelaraji ?
