### ISSUE TITLE
Hashtag at the start of a line being displayed as a header

### ISSUE THREAD

**Issue by eapl-gemugami** [sorenpeter/timeline#30]
The text `#randomMemory` at the start of a line is shown as a header instead of a hashtag
![image](https://github.com/user-attachments/assets/9ae2b50d-c605-400f-85be-e07d89dfae6a)
`<h1>randomMemory I remember [...]</h1>`
https://eapl.me/tw.txt - Line 55 - twt #iqztulq

This is wrong, as headers need a space between the Hash character `#` and the first letter as in:
[Markdown 101 - Headers](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline#h_01GY0EQVRRRB2F19HXC2BA30FG)

**Comment by aelaraji** [comment]
I used to have that on my instance as well but now, it looks just fine! 🤔

![2024-12-13_22-15-22_353x102](https://github.com/user-attachments/assets/46a20002-972c-4eef-94df-6f38d207d37f)

**Comment by eapl-gemugami** [comment]
I don't think so, let me take a look into it

**Comment by eapl-gemugami** [comment]
Yep, it's fixed now: https://eapl.me/timeline/post/iqztulq
