### ISSUE TITLE
Extend the cache to older post or load on-the-fly as needed

### ISSUE THREAD

**Issue by sorenpeter** [sorenpeter/timeline#4]
Hi @eaplmx 

If you go to http://darch.dk/timeline/gallery?profile=http://darch.dk/twtxt.txt or any other profiles gallery it shows images from posts that is not in the cache anymore?

How can we make sure that it load these posts?
Not working for timeline/Twtxt-php: http://darch.dk/timeline/post/bipn5da
Working for yarnd: https://neotxt.dk/twt/bipn5da

I would like it to always be able to load any post that is valid, since i want to use this as an archive.

Cheers, sørenpeter

**Comment by eapl-gemugami** [comment]
Hi, I'll be using this account: @eapl-gemugami 

Using that example `#bipn5da`, the root twt is the following:
> 2022-04-05T15:00:00Z	(#event) Upcomming Meetup in Copennhagen: [algolab(the_art_of_live_coding) @ Støberiet / Computer Klub](https://gath.io/uVA3cAckHXsRppB0sf551) ![](https://darch.dk/twtxt/2022-04-02_algolab_2022-04-05.jpg)

We can see that twt in this view:
https://darch.dk/timeline/?profile=http://darch.dk/twtxt.txt

But not in this one:
http://darch.dk/timeline/post/bipn5da
Shows an empty screen instead of the twt content

We can see that this instance is following [twtxt.txt](http://darch.dk/twtxt.txt) -> https://darch.dk/timeline/following
It should have the 'cache' of every .txt is following, and for some reason it's not finding twts with that hash or something.

I'll check that! Cheers!

**Comment by eapl-gemugami** [comment]
BTW @sorenpeter, does this URL http://darch.dk/timeline/post/bipn5da is currently on the `gallery` branch?

**Comment by eapl-gemugami** [comment]
I found something in base.php, where 
```
const TWTS_PER_PAGE = 50;
# and then
$twts = array_slice($twts, $startingTwt, TWTS_PER_PAGE);
```

is returning a limited list of twtxt, so the `/conv` view is trying to find the conversation `#bipn5da` in those 50 and can't find it.

I'll fix that, so in the main page the twts are paginated, and in other sections, we could find between all our following.

## Something to think about later
Processing twts from all your following in each each page request, is not really optimized memory and time-wise, although we could leave as it is for now.
For example https://darch.dk/twtxt.txt has a history of 15,786 twts, right now.

As normal usage is done, twts to look into will grow exponentially 🤔
Adding some kind of cache for threads would be a nice to have.

**Comment by sorenpeter** [comment]
Nice that you found the source of the problem. And yes I was also thinking that it might be a very expensive way I had implemented it. How do you get 15,786 twts from https://darch.dk/twtxt.txt ?

**Comment by eapl-gemugami** [comment]
> Nice that you found the source of the problem. And yes I was also thinking that it might be a very expensive way I had implemented it. How do you get 15,786 twts from https://darch.dk/twtxt.txt ?

Sorry, didn't say that correctly.
Collecting all the twits from your following is creating a whole list of 15,786 twts to search in.

**Comment by sorenpeter** [comment]
Ah, yeah that makes more sense, but not very efficient.

It works now, but maybe we should add pagination to the gallery: http://darch.dk/timeline/gallery

**Comment by eapl-gemugami** [comment]
Yeah, I was looking that pagination is started but not finished.

Nice art on /gallery, BTW!

**Comment by sorenpeter** [comment]
Coming back after being offline for some days during new year, I'm reminded that the main timeline view does not have pagination even though there is  a TWTS_PER_PAGE value in base.php.
So how can we implement this? I guess it would involve a param query of some sort, that can be used for both the main timeline and profile view.
