### ISSUE TITLE
HTML in the twt is breaking the page rendering

### ISSUE THREAD

**Issue by eapl-gemugami** [sorenpeter/timeline#5]
In https://darch.dk/timeline/?profile=http://darch.dk/twtxt.txt the Web page stops rendering in the post `#csss4xq`

```
2022-01-23T11:18:24Z	Trying out posting css and html for directe render <style>.colors div display: inline-block;	height: 100px;	width:  100px;	/*border: thin solid black;*/}/* Solids */.black {background: #000;}.red {background: #f00;}.green {background: #0f0;}.blue {background: #00f;}/* Gradients */.yellow {background: linear-gradient(to right, #f00, #ff0, #0f0);}.cyan {background: linear-gradient(to bottom, #0f0, #0ff, #00f);}.magenta-vertical {background: linear-gradient(to bottom, #f00, #f0f, #f0f);}.magenta-horisontal {background: linear-gradient(to right, #f0f, #f0f, #00f);}</style><div class="colors">	<div class="red"></div><div class="yellow"></div><div class="green"></div></div><div class="colors"><div class="magenta-vertical"></div><div class="black"></div><div class="cyan"></div></div><div class="colors">	<div class="black"></div><div class="magenta-horisontal"></div><div class="blue"></div></div>
```

This is rendered as 
```
<div class="twt-msg">
  Trying out posting css and html for directe render <style>.colors div display: inline-block;
</div>
```
I suspect the <style> not being closed is making the page to stop loading.

That gives me some thoughts:
1) Check why the twt is not shown completely
2) It's not recommended to render HTML directly from user input since it could be used maliciously.
But in the other hand avoiding it using something like [htmlspecialchars](https://www.php.net/manual/en/function.htmlspecialchars.php), will make picoblog content to stop working. 
3) I'd suggest for `timeline` to only allow Gemtext or Markdown, but not HTML.

**Comment by sorenpeter** [comment]
yeah I tried to push the limits by just posting html and css to a twt. Picoblog seem to accept it, but I'm in favor of limiting it to only markdown. I'm not familiar with gemtext, but you are welcome to add support for that too.

**Comment by eapl-gemugami** [comment]
Gemtext is a "simplified markdown" easier to parse since the first characters of the line define the behaviour:
https://smol.pub/gemtext

I use it for my blog, although I think that adding some library Markdown2HTML would be better.

**Comment by sorenpeter** [comment]
Im already using Slimdown.php for the markdown parser

**Comment by sorenpeter** [comment]
Looking at gemtext, the only thing missing compared to markdown seem to be links with the `=>` prefix, which would be easy to implement ourself

**Comment by sorenpeter** [comment]
an not sure we should support headling in twtxt. if your post need title you should write a propper blogpost and not use a microblogging system

**Comment by eapl-gemugami** [comment]
> Im already using Slimdown.php for the markdown parser

nice!

> an not sure we should support headling in twtxt. if your post need title you should write a propper blogpost and not use a microblogging system

agreed!

From Markdown, it could be:
[Emphasis](https://www.markdownguide.org/basic-syntax/#emphasis)
[Blockquotes](https://www.markdownguide.org/basic-syntax/#blockquotes-1) 
[Lists](https://www.markdownguide.org/basic-syntax/#lists-1)
[Code blocks and code snippets](https://www.markdownguide.org/basic-syntax/#code-blocks-1)
[Images](https://www.markdownguide.org/basic-syntax/#images)
[Links](https://www.markdownguide.org/basic-syntax/#links)

And possible things to disallow:
Headers
Nested blockquotes (?)
Horizontal Rules

**Comment by sorenpeter** [comment]
I think that is pretty much how i have configure Slimdown already, so not much else to do, than implementing html sanitizing in a way that does not conflict with markdown and the special twtxt/yarn syntaxes.

**Comment by sorenpeter** [comment]
@eapl-gemugami is this still a problem after I change to Parsedown.php for the markdown rendering?

**Comment by eapl-gemugami** [comment]
I've briefly checked and it seems OK, but let me take a look or even perhaps make a few tests.

**Comment by eapl-gemugami** [comment]
Looks OK, I'll close it
