### ISSUE TITLE
Refresh page doesn't load correctly the CSS style while loading files

### ISSUE THREAD

**Issue by eapl-gemugami** [sorenpeter/timeline#9]
I'm trying to run a new instance, so I'm first testing locally (on Linux Mint).

When I run `./php_server.sh` from the latest **main** branch, and visiting the following URL: `http://localhost:8000/refresh?url=https://eapl.me/twtxt.txt`

While the files are being loaded it seems like the style sheet is not being applied:
![Capture d’écran du 2024-11-28 15-55-38](https://github.com/user-attachments/assets/1537e948-a58f-4458-87fb-373f47a7e232)

And after the page finishes loading the files, it changes briefly to the usual CSS style before redirecting to the home page:
![Capture d’écran du 2024-11-28 15-58-37](https://github.com/user-attachments/assets/45b731e2-b9f5-43d8-96cb-720c422c1d50)

Is that expected for the latest state of main or do I have a bad configuration from my side? Thanks!

**Comment by sorenpeter** [comment]
After refresh it is suppose to redirect to the previous page via JavaScript back.

But I'm not sure why the CSS is not loading. if you inspect the page and look for the CSS links in the HTML <head> does theses links works?

```
<link rel="stylesheet" type="text/css" href="/timeline/libs/simple.css">
<link rel="stylesheet" type="text/css" href="/timeline/libs/timeline.css">
<link rel="stylesheet" type="text/css" href="/timeline/custom.css"> 
```

**Comment by sorenpeter** [comment]
Ah I think I had the same problem when running the server locally, but no issues when deploying online

**Comment by eapl-gemugami** [comment]
Ok, I'll try on the server to see if it works differently, thanks!

**Comment by eapl-gemugami** [comment]
Trying in the server: https://eapl.mx/timeline/refresh?url=https://eapl.mx/twtxt.txt

The page behaves similarly than on local. Keeps loading for a few seconds (I assume it's loading all the files) and briefly shows the full progress bar before redirecting to `/profile`.

I don't know how to solve it yet, showing progress after each file is loaded.

**Comment by sorenpeter** [comment]
I can't test it, since i don't know your password;)

I might also be something with the config of your server and php.

**Comment by eapl-gemugami** [comment]
I'm thinking of leaving an 'open' server with the latest **main** branch to test. 🤔

**Comment by eapl-gemugami** [comment]
You can check it with the sandbox in #18

**Comment by aelaraji** [comment]
@eapl-gemugami Do you still have this problem? I've just given it a try and it loaded just fin.

**Comment by eapl-gemugami** [comment]
Not this exact problem with CSS although it's giving some other errors:
https://twtxt-sandbox.eapl.me/timeline/

I'll close this Issue and create a new one.

**Comment by eapl-gemugami** [comment]
One of the problems I see is the same as in #23
Another one is that the refresh is not being shown progressively, but in a 'long' reload and suddenly the page is briefly shown and then redirects.
